seed: 7
cuda: -1 # use_gpu
env:
  env_type: pomdp
  env_name: Pendulum-V-v0

  num_eval_tasks: 20 # num of eval episodes

train:
  # 250*200 = 50k steps
  num_iters: 250 # to match the baseline
  buffer_size: 1000 # episodes

eval:
  eval_stochastic: false # also eval stochastic policy
  log_interval: 5 # num of iters
  save_interval: 100 # -1
  log_tensorboard: true
